### ISSUE TITLE
Great job!

### ISSUE THREAD

**Issue by tchayen** [MarcinAman/TW#2]
I just wanted to say thank you for your code. Especially the Haskell part: https://github.com/MarcinAman/TW/blob/lab4/TW4/main.hs

I will keep my fingers crossed for you when you will go through the Foat's normal form and Graphviz magic. Keep going! 💪

**Comment by osdnk** [comment]
Do your fingers connect DTE with DTE or DCE with DCE? 🤔

**Comment by tchayen** [comment]
What about DCE with DCE? They need some connection too 🤷‍♀️
